Repository wasmerio/wasmer-go, pull requests merged in 2019-12, with the labels that each got.

#94 fix(InstanceContext): Don't use uintptr for Data
  wasmer/import.go
  wasmer/instance.go
Labels: 🐞 bug, 📦 component-extension

#99 test(ci) Migrate from CircleCI to Github Actions
  .circleci/config.yml
  .github/workflows/test.yml
  README.md
  bors.toml
Labels: 🎉 enhancement, 🤖 bot, 🧪 tests

#100 chore(gh-actions) Say hello to new contributors
  .github/workflows/greetings.yml
  .github/workflows/test.yml
Labels: 🎉 enhancement, 🤖 bot

#103 test(ci) Restore Bors with Github Actions
  bors.toml
Labels: 🎉 enhancement, 🤖 bot, 🧪 tests
