Repository wasmerio/wasmer-go, pull requests merged in 2020-03, with the labels that each got.

#119 Allow importing of memory.
  wasmer/bridge.go
  wasmer/import.go
  wasmer/instance.go
  wasmer/memory.go
  wasmer/test/import_test.go
  wasmer/test/imports.go
  wasmer/test/memory_test.go
  wasmer/test/testdata/import_memory.wasm
  wasmer/test/testdata/import_memory.wat
Labels: 🎉 enhancement, 📦 component-extension, 🧪 tests

#122 doc(readme) Replace godoc.org by pkg.go.dev
  README.md
Labels: 🎉 enhancement, 📚 documentation

#124 Add check on Validate function for nil or length == 0
  wasmer/module.go
Labels: 🐞 bug, 📦 component-extension

#126 Fix an off-by-one allocation error in the Greet example
  wasmer/example_greet_test.go
Labels: 🎉 enhancement, 📚 documentation
