Repository wasmerio/wasmer-go, pull requests merged in 2020-12, with the labels that each got.

#152 fix: Imports are verified when module is instantiated
  justfile
  wasmer/import_object.go
  wasmer/instance.go
  wasmer/instance_test.go
Labels: 🐞 bug

#151 chore(ci): Update test workflow
  .github/workflows/test.yml
  bors.toml
Labels: 🎉 enhancement

#155 Update limits.go
  wasmer/limits.go
Labels: 🎉 enhancement, 📚 documentation

#159 Public API documentation
  justfile
  wasmer/engine.go
  wasmer/error.go
  wasmer/exports.go
  wasmer/exporttype.go
  wasmer/extern.go
  wasmer/externtype.go
  wasmer/function.go
  wasmer/functiontype.go
  wasmer/global.go
  wasmer/globaltype.go
  wasmer/import_object.go
  wasmer/importtype.go
  wasmer/instance.go
  wasmer/limits.go
  wasmer/memory.go
  wasmer/memorytype.go
  wasmer/module.go
  wasmer/pages.go
  wasmer/store.go
  wasmer/table.go
  wasmer/tabletype.go
  wasmer/value.go
  wasmer/valuetype.go
  wasmer/wat.go
Labels: 🎉 enhancement, 📚 documentation
