Repository wasmerio/wasmer-go, pull requests merged in 2021-06, with the labels that each got.

#267 update example command path and WASM binary inclusion
  README.md
Labels: 🐞 bug, 📚 documentation

#268 chore: Update dependencies
  Cargo.lock
  Cargo.toml
Labels: 🎉 enhancement

#264 fix: set store field in Module when calling DeserializeModule()
  wasmer/module.go
  wasmer/module_test.go
Labels: 🐞 bug
