Repository wasmerio/wasmer-go, pull requests merged in 2021-01, with the labels that each got.

#168 feat: Implement instance traps
  wasmer/instance.go
  wasmer/instance_test.go
Labels: 🐞 bug, 📦 component-extension

#169 feat: Allow setting the engine and compiler and the configuration
  wasmer/config.go
  wasmer/config_test.go
  wasmer/engine.go
  wasmer/engine_test.go
  wasmer/extern.go
  wasmer/import_object.go
Labels: 🎉 enhancement

#177 fix concurrent map read and write bug in function.go
  wasmer/function.go
Labels: 🐞 bug
