Repository wasmerio/wasmer-go, pull requests merged in 2021-03, with the labels that each got.

#229 test(function) Showcase how to get `Instance` inside a host function
  Cargo.lock
  wasmer/function_test.go
Labels: 🎉 enhancement, 📚 documentation, 🧪 tests

#230 test(ci) Test `wasmer-nightly` every night at 2am
  .github/workflows/test.yml
Labels: 🤖 bot, 🧪 tests

#242 correctly handle I64 (and other) values returned from imported functions
  wasmer/function_test.go
  wasmer/value.go
Labels: 🐞 bug

#244 fix: place `imports` in `Instance` to prevent them being freed during function execution
  wasmer/instance.go
Labels: 🐞 bug

#247 chore(cargo) Update dependencies
  Cargo.lock
Labels: dependencies, 🎉 enhancement
