Repository wasmerio/wasmer-go, pull requests merged in 2021-02, with the labels that each got.

#178 feat(wasi) Implement WASI
  wasmer/config_test.go
  wasmer/engine_test.go
  wasmer/exports.go
  wasmer/function.go
  wasmer/import_object.go
  wasmer/testdata/wasi.rs
  wasmer/testdata/wasi.wasm
  wasmer/utils_test.go
  wasmer/wasi.go
  wasmer/wasi_test.go
Labels: 🎉 enhancement, 🧪 tests

#180 feat(cross-compilation) Allow cross-compilation!
  wasmer/config.go
  wasmer/engine_test.go
  wasmer/target.go
  wasmer/target_test.go
Labels: 🎉 enhancement, 📦 component-extension, 📦 component-runtime, 🧪 tests

#185 fix(error) Lock `newErrorFromWasmer` to OS thread
  wasmer/error.go
  wasmer/instance.go
  wasmer/module.go
  wasmer/target.go
  wasmer/wasi.go
  wasmer/wat.go
Labels: 🐞 bug

#186 feat(function) Implement host function with an environment
  wasmer/function.go
  wasmer/function_test.go
Labels: 🎉 enhancement, 🧪 tests

#189 fix(wasi): Export WasiEnvironment methods
  wasmer/wasi.go
  wasmer/wasi_test.go
Labels: 🐞 bug

#193 Sequel of #190
  Cargo.lock
  README.md
  src/lib.rs
  wasmer/cgo.go
  wasmer/cgo_with_custom_wasmer_runtime.go
Labels: 🎉 enhancement, 📚 documentation, 📦 component-runtime

#207 fix(function) Avoid calling `Function.Type` for every call
  wasmer/function.go
Labels: 🎉 enhancement

#209 doc(memory) Fix documentation format
  wasmer/memory.go
Labels: 🐞 bug, 📚 documentation

#204 feat(config) Add `Config.UseSinglepassCompiler`
  wasmer/config.go
Labels: 🎉 enhancement, 📦 component-extension

#206 test(config) Use parameterized tests to check all configurations
  wasmer/config.go
  wasmer/config_test.go
Labels: 🎉 enhancement, 📦 component-extension, 🧪 tests

#213 feat(config) Add the `CompilerKind` and `EngineKind` types
  Cargo.lock
  Cargo.toml
  wasmer/config.go
  wasmer/config_test.go
Labels: 🎉 enhancement, 🐞 bug, 📚 documentation, 📦 component-extension

#211 test: Ensure the `custom_wasmer_runtime` tag works
  .github/workflows/test.yml
  README.md
  justfile
Labels: 🎉 enhancement, 📚 documentation, 🤖 bot, 🧪 tests

#220 test(config) Test with more compilers and more engines
  bors.toml
  wasmer/config_test.go
Labels: 🎉 enhancement, 🧪 tests

#221 feat(cargo) Update deps
  Cargo.lock
  wasmer/function_test.go
Labels: 🎉 enhancement, 📦 component-runtime

#223 chore: Prepare the v1.0.3
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: 🎉 enhancement, 📚 documentation
